### ISSUE TITLE
Pull Maven dependencies from and publish artifacts to stable, public Maven repositories.

### ISSUE THREAD

**Issue by msgilligan** [FDVSolutions/DynamicJasper#15]
I'm trying to build [jGNash](https://github.com/ccavanaugh/jgnash) which has a dependency on DynamicJasper. Because http://archiva.fdvs.com.ar/repository/public1/ is down, I tried to build DynamicJasper locally and install into my maven local repository. This doesn't work either because the build for DynamicJasper seems to depend on other artifacts that are hosted on the same server.

    [INFO] ------------------------------------------------------------------------
    [INFO] Building DynamicJasper 5.0.2
    [INFO] ------------------------------------------------------------------------
    [WARNING] The POM for net.sourceforge:barbecue:jar:1.1 is missing, no dependency information available
    [WARNING] The POM for ar.com.fdvs:DynamicJasper-core-fonts:jar:1.0 is missing, no dependency information available
    [WARNING] The POM for ar.com.fdvs:DynamicJasper-test-fonts:jar:1.0 is missing, no dependency information available

Setting up a [bintray](https://bintray.com) repository is fairly easy and should solve this problem, thought that's not the only option.

I realize this issue is a duplicate of #5 and #14, but it has a clearer title and those issues can be closed.

**Comment by juanalvarezg** [comment]
Hello, we are setting up a new repository (a Sonatype Nexus) it will be
available in a few days.

The old archiva is still up, but we need to restart it every 1 hour since
it is very buggy and dies very bad :(

--

*Juan Manuel Alvarez Gimenez*
JEE Architect, CTO

Office:  +54 11 5239 9899 | Cel: +54 9 11 4400 0852
Connect me on: LINKEDIN <http://ar.linkedin.com/in/jmalvarez> | SKYPE -
juan.manuel.alvarez.gimenez

*FDVSOLUTIONS | **Transformation through innovation*
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.

2015-05-02 19:31 GMT-03:00 Sean Gilligan <notifications@github.com>:

**Comment by ccavanaugh** [comment]
Poke... Any progress with the new repository?

**Comment by juanalvarezg** [comment]
Can you please try with this repo:
http://nexus.fdvs.com.ar/content/groups/public/

If it is working as expected I'll update the info on the site

thanks!

--

*Juan Manuel Alvarez Gimenez*
JEE Architect, CTO

Office:  +54 11 5239 9899 | Cel: +54 9 11 4400 0852
Connect me on: LINKEDIN <http://ar.linkedin.com/in/jmalvarez> | SKYPE -
juan.manuel.alvarez.gimenez

*FDVSOLUTIONS | Collective Innovation*
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.

2015-06-18 11:37 GMT-03:00 Craig Cavanaugh <notifications@github.com>:

**Comment by ccavanaugh** [comment]
Not working... if I poke at the URL with an web browser get an access
denied page with a link to login first.

Maven says..

[ERROR] Failed to execute goal on project jgnash-swing: Could not resolve
dependencies for project jgnash:jgnash-swing:jar:2.15.2: Failed to collect
dependencies at ar.com.fdvs:DynamicJasper:jar:5.0.2: Failed to read
artifact descriptor for ar.com.fdvs:DynamicJasper:jar:5.0.2: Could not
transfer artifact ar.com.fdvs:DynamicJasper:pom:5.0.2 from/to dynamicjasper
(http://nexus.fdvs.com.ar/content/groups/public/): Not authorized ,
ReasonPhrase:Unauthorized. -> [Help 1]

Thanks,
Craig

**Comment by smougenot** [comment]
**Nexus repo** : Access Denied :boom:
**Archiva repo** is also down :boom:

**Comment by juanalvarezg** [comment]
Please try now!

thanks for reporting the issue

--

*Juan Manuel Alvarez Gimenez*
JEE Architect, CTO

Office:  +54 11 5239 9899 | Cel: +54 9 11 4400 0852
Connect me on: LINKEDIN <http://ar.linkedin.com/in/jmalvarez> | SKYPE -
juan.manuel.alvarez.gimenez

*FDVSOLUTIONS | Collective Innovation*
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.

2015-07-02 9:24 GMT-03:00 Sylvain Mougenot <notifications@github.com>:

**Comment by ccavanaugh** [comment]
The Nexus repo appears to be working now. 

Thanks!

**Comment by juanalvarezg** [comment]
Sorry for the trouble

**Comment by smougenot** [comment]
Both are down at the moment
Sorry

**Comment by juanalvarezg** [comment]
Down until tomorrow

**Comment by juanalvarezg** [comment]
New repo! information here: http://dynamicjasper.com/download/

**Comment by smougenot** [comment]
Cool it's working
