### ISSUE TITLE
Warnings when use setTemplateFile

### ISSUE THREAD

**Issue by lrozenblyum** [FDVSolutions/DynamicJasper#17]
Hello!

I don't how whether it's a problem or now.

Whenever I use DynamicReportBuilder.setTemplateFile

I start getting a lot of warnings of kind:

 [sshexec] 13:15:32,174 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : REPORT_CONTEXT
  [sshexec] 13:15:32,174 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : REPORT_PARAMETERS_MAP
  [sshexec] 13:15:32,174 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : JASPER_REPORTS_CONTEXT
  [sshexec] 13:15:32,174 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : JASPER_REPORT
  [sshexec] 13:15:32,174 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : REPORT_CONNECTION
  [sshexec] 13:15:32,174 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : REPORT_MAX_COUNT
  [sshexec] 13:15:32,174 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : REPORT_DATA_SOURCE
  [sshexec] 13:15:32,174 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : REPORT_SCRIPTLET
  [sshexec] 13:15:32,174 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : REPORT_LOCALE
  [sshexec] 13:15:32,174 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : REPORT_RESOURCE_BUNDLE
  [sshexec] 13:15:32,174 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : REPORT_TIME_ZONE
  [sshexec] 13:15:32,174 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : REPORT_FORMAT_FACTORY
  [sshexec] 13:15:32,175 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : REPORT_CLASS_LOADER
  [sshexec] 13:15:32,175 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : REPORT_URL_HANDLER_FACTORY
  [sshexec] 13:15:32,175 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : REPORT_FILE_RESOLVER
  [sshexec] 13:15:32,175 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : REPORT_TEMPLATES
  [sshexec] 13:15:32,175 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : SORT_FIELDS
  [sshexec] 13:15:32,175 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : FILTER
  [sshexec] 13:15:32,175 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : REPORT_VIRTUALIZER
  [sshexec] 13:15:32,175 WARN  [DJJRDesignHelper] Duplicate declaration of parameter : IS_IGNORE_PAGINATION

This is reproducible even when the template is as simple as empty:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="report1" >
</jasperReport>
```

What is needed to do for those warnings not appear? Thanks!

**Comment by juanalvarezg** [comment]
I'll get rid of those messages. They are really anoying.

thank you for the reminder!

--

*Juan Manuel Alvarez Gimenez*
JEE Architect, CTO

Office:  +54 11 5239 9899 | Cel: +54 9 11 4400 0852
Connect me on: LINKEDIN <http://ar.linkedin.com/in/jmalvarez> | SKYPE -
juan.manuel.alvarez.gimenez

*FDVSOLUTIONS | Collective Innovation*
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.

2015-07-03 10:40 GMT-03:00 lrozenblyum <notifications@github.com>:

**Comment by lrozenblyum** [comment]
Thanks! It works nice !
Just a small message left we don't know how to handle:
Parameter "REPORT_LOCALE" already registered, skipping this one: en

(maybe not related to setTemplate)
