### ISSUE TITLE
New Maven repository offline

### ISSUE THREAD

**Issue by bustanil** [FDVSolutions/DynamicJasper#18]
Hi,

I tried the new Nexus repository at http://nexus.fdvs.com.ar/content/groups/public/ but I got connection timeout. Is it under maintenance?

Thanks.

**Comment by juanalvarezg** [comment]
Under mantenaince untill tomorow, sorry for the trouble

--

*Juan Manuel Alvarez Gimenez*
JEE Architect, CTO

Office:  +54 11 5239 9899 | Cel: +54 9 11 4400 0852
Connect me on: LINKEDIN <http://ar.linkedin.com/in/jmalvarez> | SKYPE -
juan.manuel.alvarez.gimenez

*FDVSOLUTIONS | Collective Innovation*
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.

2015-07-05 10:04 GMT-03:00 Bustanil Arifin <notifications@github.com>:
