### ISSUE TITLE
Dynamic Jasper webesite is not working

### ISSUE THREAD

**Issue by gayalpravin777** [FDVSolutions/DynamicJasper#20]
Hi,
I am new to the DynamicJasper reports. Need help, tutorials and examples. 
I am trying to access http://dynamicjasper.com/ but it is not working. Getting "No data received" error every time.
Didn't get dynamic jasper examples on other sites also. 
Is it in under maintenance?

 Please help?

**Comment by juanalvarezg** [comment]
Its working dude!

[image: Imagen integrada 1]

--

*Juan Manuel Alvarez Gimenez*
JEE Architect, CTO

Office:  +54 11 5239 9899 | Cel: +54 9 11 4400 0852
Connect me on: LINKEDIN <http://ar.linkedin.com/in/jmalvarez> | SKYPE -
juan.manuel.alvarez.gimenez

*FDVSOLUTIONS | Collective Innovation*
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.

2015-09-23 6:45 GMT-03:00 gayalpravin777 <notifications@github.com>:

**Comment by lrozenblyum** [comment]
It looks like not working again (without any error message, simply doesn't load...) Chrome contains ERR_EMPTY_RESPONSE

**Comment by juanalvarezg** [comment]
Dude, the site is hosted in a dedicated hosting. It works (as it is working now and since 2006) Google Analytics shows activity every single day. You may need to check your connection/browser/etc

**Comment by lrozenblyum** [comment]
Hello Juan.
I was able to reach the site via 'web proxy'!
However direct access is not working for me (tried from several ISP).
tracert shows that 
after reaching the host
ae5-20G.ar1.ROS1.ROS.gblx.net [67.16.164.165]
the next hosts are unreachable.

Maybe the hosting is blocking some big ranges of IP addresses etc.
So the conclusion:
website is up & running, but accessible not by everyone.
Maybe the issue starter faced the same issue.

**Comment by juanalvarezg** [comment]
Thank you very much for letting me know! will rise an issue to this people!

thanks again!

--

*Juan Manuel Alvarez Gimenez*
JEE Architect, CTO

Office:  +54 11 5239 9899 | Cel: +54 9 11 4400 0852
Connect me on: LINKEDIN <http://ar.linkedin.com/in/jmalvarez> | SKYPE -
juan.manuel.alvarez.gimenez

*FDVSOLUTIONS | Collective Innovation*
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.

2015-10-08 15:09 GMT-03:00 lrozenblyum <notifications@github.com>:

**Comment by juanalvarezg** [comment]
@lrozenblyum could you please give me your IP (or IP block) so I can create a ticket to the hosting service? thanks!

**Comment by lrozenblyum** [comment]
Could I contact you via juan.alvarez@fdvsolutions.com ?
Don't want exposing IPs in GitHub...

**Comment by juanalvarezg** [comment]
sure

--

*Juan Manuel Alvarez Gimenez*
JEE Architect, CTO

Office:  +54 11 5239 9899 | Cel: +54 9 11 4400 0852
Connect me on: LINKEDIN <http://ar.linkedin.com/in/jmalvarez> | SKYPE -
juan.manuel.alvarez.gimenez

*FDVSOLUTIONS | Collective Innovation*
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.

2015-10-08 15:44 GMT-03:00 lrozenblyum <notifications@github.com>:
