### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by KapuzenSohn** [FDVSolutions/DynamicJasper#21]
Hey,
I just want to ask why you don´t publish your repo to the official maven repository?
Its not very cool to first bind in your nexus so that I can use the maven dependency.

I took a quick look how you can publish to the offizial repo and it really don´t seems to be that hard.

Greetz

**Comment by juanalvarezg** [comment]
I never had the time to do that. I really want to. Once I've tried but
could not do it...

Having this in official maven repository will be the next prioritary task.

Thanks for the reminder!

--

*Juan Manuel Alvarez Gimenez*
JEE Architect, CTO

Office:  +54 11 5239 9899 | Cel: +54 9 11 4400 0852
Connect me on: LINKEDIN <http://ar.linkedin.com/in/jmalvarez> | SKYPE -
juan.manuel.alvarez.gimenez

*FDVSOLUTIONS | Collective Innovation*
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.

2015-12-10 7:35 GMT-03:00 Lars <notifications@github.com>:

**Comment by juanalvarezg** [comment]
Sorry for taking the time, but we are now publishing to maven cenrtal

http://dynamicjasper.com/2016/04/11/finally-publising-dynamicjasper-to-maven-central/
