### ISSUE TITLE
Cannot add hyperlink to chart series

### ISSUE THREAD

**Issue by jiapanlong** [FDVSolutions/DynamicJasper#23]
When add chart to report, from jasper studio, it is possible to add hyperlink to each series. When using dynamic jasper builder, cannot add hyperlink.
To fix this problem, need change the categorydateset.java and related dataset.java, check if the column have hyperlink, and do some operation.

**Comment by juanalvarezg** [comment]
Hi, actually the support for charts is very limited and mostly for paper
print. Sorry for the trouble

--

*Juan Manuel Alvarez Gimenez*
JEE Architect, CTO

Office:  +54 11 5239 9899 | Cel: +54 9 11 4400 0852
Connect me on: LINKEDIN <http://ar.linkedin.com/in/jmalvarez> | SKYPE -
juan.manuel.alvarez.gimenez

*FDVSOLUTIONS | Collective Innovation*
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.

2016-02-03 12:02 GMT-03:00 PANLONG JIA <notifications@github.com>:
