### ISSUE TITLE
Maven releases has no correspondent tags in github

### ISSUE THREAD

**Issue by asfernandes** [FDVSolutions/DynamicJasper#25]
I've started evaluating DynamicJasper, but disapointed that in maven there is a 5.0.7 release but here in github the last tag is for 5.0.4.

How can we see the correspondent source code history for these lasts revision?

Will you start create tags for next releases?

**Comment by juanalvarezg** [comment]
Sorry about that. I will add the tags.
Its just that I had to meet some requirements in the POM to make it
compliant with maven central repo polices.

Regards
Juan

--

*FDVSOLUTIONS | Collective Innovation*

*Juan Manuel Alvarez Gimenez*
CTO
Office:  +54 11 5239 9899 | Cel: +54 9 11 4400 0852
Connect me on: LINKEDIN <http://ar.linkedin.com/in/jmalvarez> | SKYPE -
juan.manuel.alvarez.gimenez
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.

2016-05-04 15:17 GMT-03:00 Adriano dos Santos Fernandes <
notifications@github.com>:
