### ISSUE TITLE
No release announcement about latest releases?

### ISSUE THREAD

**Issue by jvosloo** [FDVSolutions/DynamicJasper#26]
I'm used to seeing a blog post on dynamicjasper.com when you release a new version, but nothing since 5.0.4?

Also - what is the latest version of JasperReports that is now supported?
Last it was v6.0.3 - I need functionality provided in 6.2.2 however... supported?

**Comment by juanalvarezg** [comment]
Sorry about that. version 5.0.4 to 5.0.7 are only changes in POM until met requirements to deploy in maven central repo.
I need to check if the version 6.2.2 wokrs, or you can help me! for the project, replace JR version and run tests, if it works ok, then you are good to work with that version.
I will update, but dont know when... Im full at work these days
