### ISSUE TITLE
No reset page number option on Groups

### ISSUE THREAD

**Issue by camillealbert** [FDVSolutions/DynamicJasper#27]
With JapserReports, for Groups there is an option : 
isResetPageNumber - If true, when a new group starts, the built-in PAGE_NUMBER variable will be reset. The default value is false.

I don't find this option in DJGroup class, is it possible to add it ? Or maybe there is a workaround ?

Many thx.

**Comment by camillealbert** [comment]
Hello,

No reply 2 month later, is this lib still alive ?

Thx for your time.

Camille.

**Comment by juanalvarezg** [comment]
Hello, sorry for the late answer. It can be done since it is just a pass-through of a property.

Hope to have this on 5.0.8  sooooon

Best regards
Juan

**Comment by juanalvarezg** [comment]
Delivered! enjoy
