### ISSUE TITLE
Unable to set Excel column width

### ISSUE THREAD

**Issue by jvosloo** [FDVSolutions/DynamicJasper#28]
According to this article, I should be able to set column widths that are used during Excel export, using this property: 

`<property name="net.sf.jasperreports.export.xls.column.width" value="110"/>`

I've tried setting it as a field property like this:

```
public static AbstractColumn getStringColumn(String field, String title, int width) throws ColumnBuilderException {
    	return ColumnBuilder.getNew()
        .setColumnProperty(field, String.class.getName())
        .addFieldProperty("net.sf.jasperreports.export.xls.column.width", "200")
        .setTitle(title)
        .setWidth(width)
        .build();	 
}
```

but nothing happens. How should I be setting the element level property?

Note that setting the column width ratio property on report level works, using this:

`<property name="net.sf.jasperreports.export.xls.column.width.ratio" value="1.25f"/>`

**Comment by jvosloo** [comment]
Update issue description

**Comment by juanalvarezg** [comment]
Let me investigate this... Cannot say when I will have some progress.

**Comment by juanalvarezg** [comment]
Hi, I've been investigating and the property you want to pass, is not for a column itself, but a global property to the XLS exporter.

Bellow, an example code of the new API exporter from JasperReport. There you can see how to properly pass the parameter (check for `configuration.setColumnWidthRatio(4f)` line)

`	public static void exportReportXls(JasperPrint jp, String path) throws JRException, FileNotFoundException{
		JRXlsExporter exporter = new JRXlsExporter();

		File outputFile = new File(path);
		File parentFile = outputFile.getParentFile();
		if (parentFile != null)
			parentFile.mkdirs();
		FileOutputStream fos = new FileOutputStream(outputFile);

		SimpleXlsReportConfiguration configuration = new SimpleXlsReportConfiguration();
		exporter.setConfiguration(configuration);

		configuration.setDetectCellType(true);
		configuration.setWhitePageBackground(false);
		configuration.setIgnoreGraphics(false);
		configuration.setColumnWidthRatio(4f);

		SimpleExporterInput simpleExporterInput = new SimpleExporterInput(jp);
		OutputStreamExporterOutput simpleOutputStreamExporterOutput = new SimpleOutputStreamExporterOutput(fos);

		exporter.setExporterInput(simpleExporterInput);
		exporter.setExporterOutput(simpleOutputStreamExporterOutput);

		exporter.exportReport();

		logger.debug("Xlsx Report exported: " + path);
	}`

**Comment by jvosloo** [comment]
Hi. Setting a ratio is not so great, especially when you have many columns. I've managed to set the ratio globally using:

`DynamicReportBuilder.setProperty("net.sf.jasperreports.export.xls.column.width.ratio", "1.4f");`

but it is still not an elegant solution.

I've since also found that there are supposedly "autofit" properties which I should be able to set, which I've tried as folllows, but all with no effect:

```
return ColumnBuilder.getNew()
                            .setColumnProperty(field, String.class.getName())
                            .setTitle(title)
                            .setWidth(width)
                            .setPrintRepeatedValues(printRepeatedValues)
                            .addFieldProperty("net.sf.jasperreports.export.xls.wrap.text", "false")         // Does nothing
                            .addFieldProperty("net.sf.jasperreports.export.xls.auto.fit.column", "true")    // Does nothing
                            .addFieldProperty("net.sf.jasperreports.export.xls.auto.fit.row", "true")       // Does nothing
                            .addFieldProperty("net.sf.jasperreports.export.xls.column.width", (width*2)+"") // Does nothing
                            .build();
```

Any ideas?

**Comment by juanalvarezg** [comment]
Sorry for the late delay.

.addFieldProperty(...) will not work when exporting to excel. Its used when
data-source is like xml or json where extra metadata may be needed.

It looks like this properties, are to be applied to the static-text and
text-field elements in the design and DJ is not doing this right now.

I will put some time to pass this properties to the text-elements and see
what happens.

But cannot promise when :(

Regards

--

*FDVSOLUTIONS | Collective Innovation*

*Juan Manuel Alvarez Gimenez*
CTO
Office:  +54 11 5239 9899 | Cel: +54 9 11 4400 0852
Connect me on: LINKEDIN <http://ar.linkedin.com/in/jmalvarez> | SKYPE -
juan.manuel.alvarez.gimenez
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.

2016-08-19 4:42 GMT-03:00 Johan Vosloo <notifications@github.com>:
