### ISSUE TITLE
Starting page number feature

### ISSUE THREAD

**Issue by nerdknight** [FDVSolutions/DynamicJasper#30]
I made a [patch](https://github.com/nerdknight/DynamicJasper/commit/4632bda4c66538af3f28ddecf0cbb51242d26def) to set the first page number when adding autotext to the FastReportBuilder, if you are interested in this feature I 'll create a pull request

**Comment by juanalvarezg** [comment]
Excellent Job! 
Please create an example like others in the test folder that demonstrates how to use it.
You may call the test "PageNumberOffsetTest"

**Comment by nerdknight** [comment]
Done, added [PageNumberOffsetTest.java](https://github.com/nerdknight/DynamicJasper/blob/master/src/test/java/ar/com/fdvs/dj/test/PageNumberOffsetTest.java), it is based on AutotextReportTest

**Comment by juanalvarezg** [comment]
Thank you!

Please create the pull request!

--

*FDVSOLUTIONS | Collective Innovation*

*Juan Manuel Alvarez Gimenez*
CTO
Office:  +54 11 5239 9899 | Cel: +54 9 11 4400 0852
Connect me on: LINKEDIN <http://ar.linkedin.com/in/jmalvarez> | SKYPE -
juan.manuel.alvarez.gimenez
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.

2016-07-20 10:13 GMT-03:00 nerdknight <notifications@github.com>:

**Comment by juanalvarezg** [comment]
merged!
