### ISSUE TITLE
pdf export problem

### ISSUE THREAD

**Issue by Doaa94** [FDVSolutions/DynamicJasper#37]
I am using dynamicjasper 5.0.4 with primefaces 5.3 and jsf 2.2 I tried to use different versions of itext library and others libraries but i get many errors I want to know the most appropriate version For use with these technology

thanks 
Doaa

**Comment by juanalvarezg** [comment]
Im affraid you have to fix up your classpath

**Comment by Doaa94** [comment]
how?? can you  describe this in details

**Comment by juanalvarezg** [comment]
Sorry, that is something very particular of your project.
