### ISSUE TITLE
GET http://dynamicjasper.com ERR_ZERO_SIZE_OBJECT

### ISSUE THREAD

**Issue by ciukstar** [FDVSolutions/DynamicJasper#39]
$curl -v --head http://dynamicjasper.com
* Rebuilt URL to: http://dynamicjasper.com/
*   Trying 200.58.119.89...
* Connected to dynamicjasper.com (200.58.119.89) port 80 (#0)
> HEAD / HTTP/1.1
> Host: dynamicjasper.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 502 Bad Gateway
HTTP/1.0 502 Bad Gateway
< Server: squid
Server: squid
< Date: Fri, 30 Sep 2016 10:26:09 GMT
Date: Fri, 30 Sep 2016 10:26:09 GMT
< Content-Type: text/html
Content-Type: text/html
< Content-Length: 945
Content-Length: 945
< Expires: Fri, 30 Sep 2016 10:26:09 GMT
Expires: Fri, 30 Sep 2016 10:26:09 GMT
< X-Squid-Error: ERR_ZERO_SIZE_OBJECT 0
X-Squid-Error: ERR_ZERO_SIZE_OBJECT 0
< X-Cache: MISS from gw.centp.ru
X-Cache: MISS from gw.centp.ru
< Connection: close
Connection: close

**Comment by juanalvarezg** [comment]
Maybe a temporary downtime. its working now.

Thank you!

**Comment by ciukstar** [comment]
No. Is there another way to get to documentation, tutorials and examples? Thanks!

**Comment by juanalvarezg** [comment]
Sorry, its all there.

Try using an anonymous proxy if where you are has limited internet

--

*Juan Manuel Alvarez Gimenez*
CTO

Office:  +54 11 5239 9899
Celular: +54 9 11 4400 0852
Skype: juan.manuel.alvarez.gimenez
Connect me on: LINKEDIN <http://ar.linkedin.com/in/jmalvarez>

*FDVSOLUTIONS | Collective Innovation*
Avenida Belgrano 1580 2º piso C1093AAA , Buenos Aires, Argentina.
www.fdvsolutions.com


This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.

2016-09-30 10:26 GMT-03:00 ciukstar <notifications@github.com>:

**Comment by ciukstar** [comment]
I reached the site through anonymous proxy. Thanks a lot!
