### ISSUE TITLE
Source code for Dynamic Jasper grails plugin?

### ISSUE THREAD

**Issue by basejump** [FDVSolutions/DynamicJasper#40]
we are looking at possibly making it compatible with 2.5 and 3+

**Comment by juanalvarezg** [comment]
Hi, I've just spent 1 hour looking for the code in our very old (deprecated SVN) and could not find it.
but you can download de plugin from here: http://repo.grails.org/grails/plugins/org/grails/plugins/dynamic-jasper/0.6/dynamic-jasper-0.6.zip
The source code is there

**Comment by basejump** [comment]
thanks so much for looking. I grabbed the zip and am using that source
