### ISSUE TITLE
Font API inconsistency

### ISSUE THREAD

**Issue by ccavanaugh** [FDVSolutions/DynamicJasper#49]
As of 5.1.0 the Font constructor only takes an int for size.

setFontSize and getFontSize should be int values only as well.

**Comment by ccavanaugh** [comment]
Error on my part

**Comment by MatheusRadeski** [comment]
Estou com erro justamente nessa parte, oque poderia ser?
Caused by: java.lang.NoSuchMethodError: net.sf.jasperreports.engine.base.JRBaseStyle.setFontSize(Ljava/lang/Float;)V
